#!/bin/bash

# Set up XDG_CONFIG_HOME
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"

# Make links
ln -sf "$PWD/.bashrc" "$HOME"/.bashrc
ln -sf "$PWD/config.nix" "$XDG_CONFIG_HOME"/nixpkgs/config.nix

# Clone nvim config
echo "Cloning nvim config from repo"
git clone https://github.com/timo-y/nvim.git "$XDG_CONFIG_HOME"/nvim
echo "Nvim config cloned."

# Install dependencies
echo "Install packages via nix"
nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
nix-channel --update

# Install `myPackages` defined in config.nix
nix-env -f "$XDG_CONFIG_HOME/nixpkgs/config.nix" -iA myPackages

echo "All packages have been installed."
