#!/bin/bash

# Set up XDG_CONFIG_HOME
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"

# Make links
ln -sf "$PWD/.bashrc" "$HOME"/.bashrc

# Clone nvim config
echo "Cloning nvim config from repo"
git clone https://github.com/timo-y/nvim.git "$XDG_CONFIG_HOME"/nvim
echo "Nvim config cloned."

# Install dependencies
# Install Nix packages from config.nix
nix-env -iA nixpkgs.myPackages

# Brew alternative
# packages=(
# ripgrep,
# npm
# )
# # Iterate over the array and install each package
# for package in "${packages[@]}"; do
#   echo "Installing $package..."
#   /home/linuxbrew/.linuxbrew/bin/brew install "$package"
# done

echo "All packages have been installed."
