icons_format = "{icon}"

[theme]
theme = "srcery"
[theme.overrides]

[icons]
icons = "awesome4"
# [icons.overrides]
# bat = ["|E|", "|_|", "|=|", "|F|"]
# bat_charging = "|^| "

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

# [[block]]
# block = "disk_space"
# path = "/home"
# info_type = "available"
# alert_unit = "GB"
# interval = 20
# warning = 20.0
# alert = 10.0
# format = " $icon home: $available.eng(w:2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "custom"
command = "echo '\uf0ac '`curl http://checkip.amazonaws.com`" # assumes fontawesome icons
interval = 60

[[block]]
block = "vpn"
driver = "nordvpn"
interval = 30
# Format when connected (shows icon + country)
format_connected = " $icon $country "
# Format when disconnected (shows icon + 'Disconnected')
format_disconnected = " $icon DC'd "
# Visual states (colors)
state_connected = "good"
state_disconnected = "warning"

[[block]]
block = "vpn"
driver = "tailscale"
interval = 30
# Format when connected (shows icon + country)
format_connected = " $icon TS up "
# Format when disconnected (shows icon + 'Disconnected')
format_disconnected = " $icon TS down "
# Visual states (colors)
state_connected = "good"
state_disconnected = "warning"

[[block]]
block = "custom"
cycle = [
  "echo '{\"icon\": \"net_wireless\", \"text\": \"'$(iwctl station wlan0 show | awk '/Connected network/ {print $3}')'\"}'",
  "echo '{\"icon\": \"net_wireless\", \"text\": \"'$(iwctl station wlan0 show | awk '/ConnectedBss/ {print $2}')'\"}'"
]
interval = 60
json = true
format = " $icon  $text "

# [[block]]
# block = "custom"
# command = "echo xkcd"
# interval = "once"
# [[block.click]]
# button = "left"
# cmd = "xdg-open 'https://c.xkcd.com/random/comic/'"

[[block]]
block = "battery"
format = " $icon $percentage {$time_remaining.dur(hms:true, min_unit:m) |}"

